src/CAIF/SharedBundle/Entity/Person.php
<?php

namespace CAIF\SharedBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * @ORM\Entity()
 * @UniqueEntity(fields={"email"}, message="This email address is already in use.")
 * @UniqueEntity(fields={"username"}, message="This username is not available.")
 * @ORM\Table(name="person")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="entity", type="string")
 * @ORM\DiscriminatorMap({
 *      "host"    = "Host",
 *      "student" = "Student",
 *      "admin"   = "Admin",
 * })
 */
abstract class Person implements AdvancedUserInterface
{
    public function getEntityType()
    {
        $classParts = explode('\\', get_called_class());
        return array_pop($classParts);
    }

    public static function getCountryList($showNP = true)
    {
        if ($showNP) {
            $np = ["any" => 'No Preference'];
        }

        $list = [
            "AF" => 'Afghanistan',
            "AL" => 'Albania',
            "DZ" => 'Algeria',
            "AS" => 'American Samoa',
            "AD" => 'Andorra',
            "AO" => 'Angola',
            "AI" => 'Anguilla',
            "AQ" => 'Antarctica',
            "AG" => 'Antigua and Barbuda',
            "AR" => 'Argentina',
            "AM" => 'Armenia',
            "AW" => 'Aruba',
            "AU" => 'Australia',
            "AT" => 'Austria',
            "AZ" => 'Azerbaijan',
            "BS" => 'Bahamas',
            "BH" => 'Bahrain',
            "BD" => 'Bangladesh',
            "BB" => 'Barbados',
            "BY" => 'Belarus',
            "BE" => 'Belgium',
            "BZ" => 'Belize',
            "BJ" => 'Benin',
            "BM" => 'Bermuda',
            "BT" => 'Bhutan',
            "BO" => 'Bolivia',
            "BA" => 'Bosnia and Herzegowina',
            "BW" => 'Botswana',
            "BV" => 'Bouvet Island',
            "BR" => 'Brazil',
            "IO" => 'British Indian Ocean Territory',
            "BN" => 'Brunei Darussalam',
            "BG" => 'Bulgaria',
            "BF" => 'Burkina Faso',
            "BI" => 'Burundi',
            "KH" => 'Cambodia',
            "CM" => 'Cameroon',
            "CA" => 'Canada',
            "CV" => 'Cape Verde',
            "KY" => 'Cayman Islands',
            "CF" => 'Central African Republic',
            "TD" => 'Chad',
            "CL" => 'Chile',
            "CN" => 'China',
            "CX" => 'Christmas Island',
            "CC" => 'Cocos (Keeling) Islands',
            "CO" => 'Colombia',
            "KM" => 'Comoros',
            "CG" => 'Congo',
            "CD" => 'Congo, the Democratic Republic of the',
            "CK" => 'Cook Islands',
            "CR" => 'Costa Rica',
            "CI" => 'Cote d\'Ivoire',
            "HR" => 'Croatia (Hrvatska)',
            "CU" => 'Cuba',
            "CY" => 'Cyprus',
            "CZ" => 'Czech Republic',
            "DK" => 'Denmark',
            "DJ" => 'Djibouti',
            "DM" => 'Dominica',
            "DO" => 'Dominican Republic',
            "TP" => 'East Timor',
            "EC" => 'Ecuador',
            "EG" => 'Egypt',
            "SV" => 'El Salvador',
            "GQ" => 'Equatorial Guinea',
            "ER" => 'Eritrea',
            "EE" => 'Estonia',
            "ET" => 'Ethiopia',
            "FK" => 'Falkland Islands (Malvinas)',
            "FO" => 'Faroe Islands',
            "FJ" => 'Fiji',
            "FI" => 'Finland',
            "FR" => 'France',
            "FX" => 'France, Metropolitan',
            "GF" => 'French Guiana',
            "PF" => 'French Polynesia',
            "TF" => 'French Southern Territories',
            "GA" => 'Gabon',
            "GM" => 'Gambia',
            "GE" => 'Georgia',
            "DE" => 'Germany',
            "GH" => 'Ghana',
            "GI" => 'Gibraltar',
            "GR" => 'Greece',
            "GL" => 'Greenland',
            "GD" => 'Grenada',
            "GP" => 'Guadeloupe',
            "GU" => 'Guam',
            "GT" => 'Guatemala',
            "GN" => 'Guinea',
            "GW" => 'Guinea-Bissau',
            "GY" => 'Guyana',
            "HT" => 'Haiti',
            "HM" => 'Heard and Mc Donald Islands',
            "VA" => 'Holy See (Vatican City State)',
            "HN" => 'Honduras',
            "HK" => 'Hong Kong',
            "HU" => 'Hungary',
            "IS" => 'Iceland',
            "IN" => 'India',
            "ID" => 'Indonesia',
            "IR" => 'Iran (Islamic Republic of)',
            "IQ" => 'Iraq',
            "IE" => 'Ireland',
            "IL" => 'Israel',
            "IT" => 'Italy',
            "JM" => 'Jamaica',
            "JP" => 'Japan',
            "JO" => 'Jordan',
            "KZ" => 'Kazakhstan',
            "KE" => 'Kenya',
            "KI" => 'Kiribati',
            "KP" => 'Korea, Democratic People\'s Republic of',
            "KR" => 'Korea, Republic of',
            "KW" => 'Kuwait',
            "KG" => 'Kyrgyzstan',
            "LA" => 'Lao People\'s Democratic Republic',
            "LV" => 'Latvia',
            "LB" => 'Lebanon',
            "LS" => 'Lesotho',
            "LR" => 'Liberia',
            "LY" => 'Libyan Arab Jamahiriya',
            "LI" => 'Liechtenstein',
            "LT" => 'Lithuania',
            "LU" => 'Luxembourg',
            "MO" => 'Macau',
            "MK" => 'Macedonia, The Former Yugoslav Republic of',
            "MG" => 'Madagascar',
            "MW" => 'Malawi',
            "MY" => 'Malaysia',
            "MV" => 'Maldives',
            "ML" => 'Mali',
            "MT" => 'Malta',
            "MH" => 'Marshall Islands',
            "MQ" => 'Martinique',
            "MR" => 'Mauritania',
            "MU" => 'Mauritius',
            "YT" => 'Mayotte',
            "MX" => 'Mexico',
            "FM" => 'Micronesia, Federated States of',
            "MD" => 'Moldova, Republic of',
            "MC" => 'Monaco',
            "MN" => 'Mongolia',
            "MS" => 'Montserrat',
            "MA" => 'Morocco',
            "MZ" => 'Mozambique',
            "MM" => 'Myanmar',
            "NA" => 'Namibia',
            "NR" => 'Nauru',
            "NP" => 'Nepal',
            "NL" => 'Netherlands',
            "AN" => 'Netherlands Antilles',
            "NC" => 'New Caledonia',
            "NZ" => 'New Zealand',
            "NI" => 'Nicaragua',
            "NE" => 'Niger',
            "NG" => 'Nigeria',
            "NU" => 'Niue',
            "NF" => 'Norfolk Island',
            "MP" => 'Northern Mariana Islands',
            "NO" => 'Norway',
            "OM" => 'Oman',
            "PK" => 'Pakistan',
            "PW" => 'Palau',
            "PA" => 'Panama',
            "PG" => 'Papua New Guinea',
            "PY" => 'Paraguay',
            "PE" => 'Peru',
            "PH" => 'Philippines',
            "PN" => 'Pitcairn',
            "PL" => 'Poland',
            "PT" => 'Portugal',
            "PR" => 'Puerto Rico',
            "QA" => 'Qatar',
            "RE" => 'Reunion',
            "RO" => 'Romania',
            "RU" => 'Russian Federation',
            "RW" => 'Rwanda',
            "KN" => 'Saint Kitts and Nevis',
            "LC" => 'Saint LUCIA',
            "VC" => 'Saint Vincent and the Grenadines',
            "WS" => 'Samoa',
            "SM" => 'San Marino',
            "ST" => 'Sao Tome and Principe',
            "SA" => 'Saudi Arabia',
            "SN" => 'Senegal',
            "SC" => 'Seychelles',
            "SL" => 'Sierra Leone',
            "SG" => 'Singapore',
            "SK" => 'Slovakia (Slovak Republic)',
            "SI" => 'Slovenia',
            "SB" => 'Solomon Islands',
            "SO" => 'Somalia',
            "ZA" => 'South Africa',
            "GS" => 'South Georgia and the South Sandwich Islands',
            "ES" => 'Spain',
            "LK" => 'Sri Lanka',
            "SH" => 'St. Helena',
            "PM" => 'St. Pierre and Miquelon',
            "SD" => 'Sudan',
            "SR" => 'Suriname',
            "SJ" => 'Svalbard and Jan Mayen Islands',
            "SZ" => 'Swaziland',
            "SE" => 'Sweden',
            "CH" => 'Switzerland',
            "SY" => 'Syrian Arab Republic',
            "TW" => 'Taiwan',
            "TJ" => 'Tajikistan',
            "TZ" => 'Tanzania, United Republic of',
            "TH" => 'Thailand',
            "TG" => 'Togo',
            "TK" => 'Tokelau',
            "TO" => 'Tonga',
            "TT" => 'Trinidad and Tobago',
            "TN" => 'Tunisia',
            "TR" => 'Turkey',
            "TM" => 'Turkmenistan',
            "TC" => 'Turks and Caicos Islands',
            "TV" => 'Tuvalu',
            "UG" => 'Uganda',
            "UA" => 'Ukraine',
            "AE" => 'United Arab Emirates',
            "GB" => 'United Kingdom',
            "US" => 'United States',
            "UM" => 'United States Minor Outlying Islands',
            "UY" => 'Uruguay',
            "UZ" => 'Uzbekistan',
            "VU" => 'Vanuatu',
            "VE" => 'Venezuela',
            "VN" => 'Viet Nam',
            "VG" => 'Virgin Islands (British)',
            "VI" => 'Virgin Islands (U.S.)',
            "WF" => 'Wallis and Futuna Islands',
            "EH" => 'Western Sahara',
            "YE" => 'Yemen',
            "YU" => 'Yugoslavia',
            "ZM" => 'Zambia',
            "ZW" => 'Zimbabwe',
        ];

        if ($showNP) {
            return array_merge($np, $list);
        }

        return $list;
    }

    /**
     * @ORM\Id()
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(min=3, max=255)
     * @ORM\Column(name="username", type="string", length=255)
     */
    protected $username;

    /**
     * @ORM\Column(name="password", type="string", length=255)

src/CAIF/SharedBundle/Resources/views/Shared/layout.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <script src="//use.fonticons.com/2d2cc9ab.js"></script>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" type="image/ico" href="{{ asset('bundles/caifshared/images/favicon.png') }}"/>

        <title>{% block title %}CAIF{% endblock %}</title>

        {% block stylesheets %}
            <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
            {% stylesheets
                '@CAIFSharedBundle/Resources/public/css/bootstrap/bootstrap.css'
                '@CAIFSharedBundle/Resources/public/css/custom.css'
                '@CAIFSharedBundle/Resources/public/css/bootstrap-datepicker/bootstrap-datepicker.css'
                '@CAIFSharedBundle/Resources/public/css/bootstrap-timepicker/bootstrap-timepicker.css'
                '@CAIFSharedBundle/Resources/public/css/custom-typeahead.css'
            %}
                <link rel="stylesheet" href="{{ asset_url }}" />
            {% endstylesheets %}
        {% endblock %}


        <script src='https://www.google.com/recaptcha/api.js'></script>

        <style type="text/css">
            @font-face {
                font-family: "Lato-Light";
                src: url("{{ asset('bundles/caifshared/fonts/Lato-Light.ttf') }}")
            }
            @font-face {
                font-family: "Lato";
                src: url("{{ asset('bundles/caifshared/fonts/Lato-Light.ttf') }}")
            }
        </style>
    </head>

    <body>
        {% include 'CAIFSharedBundle:Shared:nav.html.twig' %}

        {% block page_title %}
            <div class="page-heading">
                <div class="container">
                    <h1 class="color-white main-heading" style="padding-left: 30px;">
                        {% block page_title_header %}{% endblock %}
                    </h1>
                </div>
            </div>
        {% endblock %}

        {% block pre_content %}
        {% endblock %}

        {% block flash_messages %}
            {% set flashTypes = [ 'info', 'warning', 'error', 'success'] %}
            {% set flashTypeMap = {
                'info' : 'info',
                'warning' : 'warning',
                'error' : 'danger',
                'success' : 'success',
            } %}
            {% for flashType in flashTypes %}
                {% for flashMessage in app.session.flashbag.get(flashType) %}
                    <div class="hidden-print alert alert-dismissible alert-{{ flashTypeMap[flashType] }}" role="alert" style="margin: -10px 0px 0px 0px;">
                        <div class="container">
                            <strong>
                                {{ flashMessage|raw }}
                            </strong>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
        {% endblock %}

        {% block full_content %}
            <div class="content">
                <div id="page-wrapper">
                    {% block container_content %}
                        <div class="container" style="padding-top: 30px; padding-bottom: 30px;">
                            {% block content %}
                            {% endblock %}
                            <br>
                        </div>
                    {% endblock %}
                </div>
            </div>
        {% endblock %}
        <div class="content">
            <div id="page-wrapper">
                <hr style="margin: 0px;">
                {% block footer %}
                    <footer style="padding-top: 20px;">
                        <div class="container">
                            <div class="row hidden-xs" style="padding: 10px 0px 30px 0px;">
                                <div class="col-sm-3">
                                    <img src="{{ asset('bundles/caifshared/images/logoOrangeSimple.png') }}" style="width: 100%;">
                                </div>
                                <div class="col-sm-9">
                                    <div class="row" style="margin-top: 10px;">
                                        <div class="col-md-4">
                                            <a href="{{ path('caif_shared_student_form') }}" class="btn btn-caif btn-block btn-lg">
                                                Student Form
                                            </a>
                                        </div>
                                        <div class="col-md-4">
                                            <a href="{{ path('caif_shared_host_form') }}" class="btn btn-caif btn-block btn-lg">
                                                Host Form
                                            </a>
                                        </div>
                                        <div class="col-md-4">
                                            <a href="{{ path('caif_shared_contact') }}" class="btn btn-caif btn-block btn-lg">
                                                Contact Us
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="visible-xs">
                                <center class="light-grey">
                                    <a href="https://www.facebook.com/groups/ClemsonAreaInternationalFriendship/" style="font-size: 30px;" class="light-grey" target="_blank">
                                        {{ icon('facebook-square') }}
                                    </a>
                                    <br>
                                    Copyright &copy; {{ "now"|date('Y') }}
                                    Clemson Area International Friendship
                                </center>
                            </div>
                        </div>
                        <div class="hidden-xs">
                            <div class="footer-nav">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <h4>About</h4>
                                            <a href="{{ path('caif_shared_about') }}">Who We Are</a>
                                            <br>
                                            <a href="{{ path('caif_shared_mission') }}">Mission</a>
                                            <br>
                                        </div>
                                        <div class="col-md-3">
                                            <h4>Host Program</h4>
                                            <a href="{{ path('caif_shared_host_conversation') }}">Intro to Hosting Students</a>
                                            <br>
                                            <a href="{{ path('caif_shared_host_guidelines') }}">Host Guidelines</a>
                                            <br>
                                            <a href="{{ path('caif_shared_host_form') }}">New Host Form</a>
                                            <br>
                                        </div>
                                        <div class="col-md-3">
                                                <h4>Student Program</h4>
                                                <a href="{{ path('caif_shared_student_guidelines') }}">Student Guidelines</a>
                                                <br>
                                                <a href="{{ path('caif_shared_testimonials') }}">Testimonials</a>
                                                <br>
                                                <a href="{{ path('caif_shared_student_form') }}">New Student Form</a>
                                                <br>
                                            </div>
                                        <div class="col-md-3">
                                            <h4>Helpful Resources</h4>
                                            <a href="{{ path('caif_shared_event_intl_club') }}">International Club (Bridges Int'l)</a>
                                            <br>
                                            <a href="{{ path('caif_shared_event_wives_club') }}">International Wives Club</a>
                                            <br>
                                            <a href="http://www.clemsoncommunitycare.org/" target="_blank">Clemson Community Care</a>
                                            <br>
                                            <a href="https://docs.google.com/presentation/d/1A047101edGc_aDRClVG3GMki5VeQSBofhLwoXjgR6Eo/edit#slide=id.p4" target="_blank">Buying a Used Car</a>
                                            <br>
                                            <a href="{{ path('caif_shared_event_english_classes') }}">English Classes</a>
                                            <br>
                                            <a href="{{ path('caif_shared_faq') }}">FAQ</a>
                                            <br>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div style="background-color: #ddd; padding: 10px 0px;">
                                <div class="container">
                                    <h4 class="light-grey">
                                        <a href="https://www.facebook.com/groups/ClemsonAreaInternationalFriendship/" style="font-size: 38px;" class="light-grey" target="_blank">
                                            {{ icon('facebook-square') }}
                                        </a>
                                        {# <a href="#" class="btn btn-footer" style="margin-top: -15px;">
                                            Donate
                                        </a> #}

                                        <span class="pull-right" style="padding-top: 10px;">
                                            &copy; {{ "now"|date('Y') }} Clemson Area International Friendship
                                        </span>
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </footer>
                {% endblock %}
            </div>
        </div>

        {% block javascripts %}

            {% javascripts
                'bundles/caifshared/js/jquery-1.11.1.min.js'
                'bundles/caifshared/js/lib/bootstrap/bootstrap.js'
                'bundles/caifshared/js/lib/bootstrap-datepicker/bootstrap-datepicker.js'
                'bundles/caifshared/js/lib/bootstrap-timepicker/bootstrap-timepicker.js'
                'bundles/caifshared/js/bloodhound.js'
                'bundles/caifshared/js/typeahead.js'
                'bundles/caifshared/js/custom-typeahead.js'
            %}
                <script src="{{ asset_url }}"></script>
            {% endjavascripts %}

            <script>
                $('.js-row-click').on('click', function(e) {
                    window.location.href = $(this).attr('id');
                })

                /* timepicker */
                $('.timepicker').timepicker({showInputs: false});


                /* datepicker */
                $('.datepicker').datepicker();
                $('tbody').on('click', function(e){
                    $('.datepicker-days').parent().hide();
                })

                var is_chrome = window.chrome;
                if ( is_chrome ) {
                    $('input[type=date]').on('click', function(event) {
                        event.preventDefault();
                    });

                    $('input[type=time]').on('click', function(event) {
                        event.preventDefault();
                    });
                }
            </script>

        {% endblock %}
    </body>
</html>

src/CAIF/SharedBundle/Resources/views/Shared/nav.html.twig
<nav class="navbar" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">CAIF</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                {# <li style="padding-top: 10px; margin-right: 20px;">
                    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                        <input type="hidden" name="cmd" value="_s-xclick" />
                        <input type="hidden" name="hosted_button_id" value="A4YHE4E3NNPJ4" />
                        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                        <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
                    </form>
                </li> #}
                <li style="padding-top: 10px; margin-right: 20px;">
                    <form target="paypal" action="https://www.paypal.com/cgi-bin/webscr" method="post">
                        <input type="hidden" name="cmd" value="_s-xclick">
                        <input type="hidden" name="hosted_button_id" value="A4YHE4E3NNPJ4">
                        <input type="submit" class="btn btn-header" role="button" value="Donate" style="padding: 10px 25px; font-size: 1em; margin-top: 2px;">
                    </form>
                </li>
                <li>
                    <a href="{{ path('caif_shared_contact') }}">
                        Contact Us
                    </a>
                </li>

                {% if app.user is not null %}
                    <li class="dropdown">
                        <a class="dropdown-toggle user-dropdown" data-toggle="dropdown" href="#">
                            <span>
                                {{ app.user }}
                            </span>
                            <i class="fa fa-caret-down user-dropdown-toggle"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            {% if is_granted('ROLE_ADMIN') %}
                                <li>
                                    <a href="{{ path('caif_manage_index') }}">
                                        {{ icon('cogs') }}
                                        Admin
                                    </a>
                                </li>
                            {% endif %}
                            {% if app.user.entityType == "Host" or app.user.entityType == "Student" %}
                                <li>
                                    <a href="{{ path('caif_shared_profile_' ~ app.user.entityType|lower, {'person': app.user.id}) }}">
                                        {{ icon('user') }}
                                        My Profile
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a href="{{ path('caif_shared_faq') }}">
                                    {{ icon('question-circle') }}
                                    Help
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="/logout">
                                    {{ icon('power-off') }}
                                    Logout
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="dropdown">
                        <a class="dropdown-toggle login-dropdown" data-toggle="dropdown" href="#">
                            <span>
                                Login
                            </span>
                            <i class="fa fa-caret-down login-dropdown-toggle"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="/login">
                                    {{ icon('sign-in') }}
                                    Login
                                </a>
                            </li>
                            <li>
                                <a href="{{ path('caif_shared_faq') }}">
                                    {{ icon('question-circle') }}
                                    Help
                                </a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>

            {% set primary_navigation = knp_menu_get('CAIFSharedBundle:Builder:mainMenu') %}
            {{ knp_menu_render(primary_navigation, { 'style': 'navbar', 'depth' : 2 }) }}
        </div>
    </div>
</nav>